### ISSUE TITLE
Commercial catches

### ISSUE THREAD

**Issue by aliwhitman** [shcaba/Sebastes_melanops_OR#9]
Otherwise known as why they're late!  Sorry :( 

There are currently two issues with commercial catch. First, I will need to confirm our fleet structure.  Our only discussions about this have been related to combining the "dead" and "live" fleets. So to this end, I have currently structured commercial landings into a trawl and non-trawl fleet (the combination of live and dead fleets from the last assessment).  

Trawl <- PacFIN gear codes 360:393 (includes mid-water trawl and all other trawl types)
Non-Trawl <- PacFIN gear codes c(120:350, 400:490) (everything else! Hook and line, longline, pot, troll)

If we can confirm the fleets that were originally included in the trawl, live and dead fleets in the 2015 model, that would be helpful... because of issue 2 - commercial catches seem to be different across the board when I compare them with the previous assessment. 

- Even recent catches (e.g. PacFIN only era - 2000 - 2022) are slightly different. Within a mt most years but enough to be annoying and across all years that I've looked at.

- I would expect some differences from 1986 - 1999, as these years now have the URCK reconstruction, but in some years they are large and not all accounted for by the URCK reconstruction. 

- Finally, there are also differences in the historical period (1986 and back) because the 2015 assessment apparently tinkered with the historical reconstruction, which was available at that time, and provided an alternative time series for part of that time period (1949 - 1986). Their justification was high interannual variability in the proportion of blacks, which I am less convinced of looking at the data (I can provide these if we all want to look at them).  I'm unsure if they were looking at an early version of the reconstruction (might be something to check with Vlada about as she was a co-author, the document for that reconstruction is short on details).  The tinkering substantially reduced the removals in the model from the version that I am now using. 

So going to need some feedback on this to resolve it and get us our commercial catches. Something to discuss on Monday morning. I will try to get some figures together to facilitate comparisons.

**Comment by aliwhitman** [comment]
I am going to try to summarize what I have learned from the last week of digging, so that we can discuss at our Monday morning meeting next week.  

- since the commercial catch reconstruction had just been completed prior to the last assessment, no one noticed until the black rockfish assessment that there was high interannual variability in black rockfish trawl landings with unreasonable magnitudes of catch in many years (1940s - mid1980s). 
- ODFW (Patrick Mirick) provided two alternatives of reconstructed trawl landings and the second was chosen to use in the 2015 assessment 
- this reconstruction used similar data to the Karnowski reconstruction but applied comps at a finer scale and aggregated comps to increase sample size 
- rockfish category-level landings were investigated across multiple data sources, including the FSUS reports (used in Karnowski and Mirick reconstructions) and were found to be similar in magnitude across sources (where overlap actually did occur) 
- however, species compositions differed among sources and was suggested as the primary issue with estimating species-specific trawl landings
- I have detailed notes on what data sources were used and how for species compositions for both the Karnowski reconstruction and the Mirick reconstruction
- I also have most of the source files used to create the Mirick reconstruction 

With regards to allocation N/S of the OR-WA border: 

- the Karnowski catch reconstruction did not account for this at all - based solely on port of landing
- Mirick used additional sources of data (plus paper copies of the same source as the Karnowski that had additional information) to allocate a proportion of the coastwide trawl landings to PFMC 3A (or the CR district in early years)
- Mirick developed apportionments using two sources of data (1940 - 1993 - ODFW species compositions from the Douglas publication, annual proportions from the trawl logbook from 1994 - 2013) to separate fish within 3A

Generally, the recommendations that I'm hearing from ODFW staff include: 

- the Mirick reconstruction is absolutely a more accurate estimate of trawl landings for black rockfish (a common but minor species in trawl landings) - staff recommend using this reconstruction as with the last assessment
- nearshore trawling was common during the historic time period in question, and even off of WA, where there is limited high relief rocky habitat, there are significant hot spots that have persisted over time and a bunch of less ideal but still rocky habitat with low to moderate densities 
- it also makes sense to allocate a large chunk of 3A blacks to north of the border so there is strong support for that too 
- (note that we could continue using logbook data to separate the most recent years using the same methodology)
- there are strong differences in species compositions by depth, though I am unsure we have data to speak to these at this time

HAPPY FRIDAY!

**Comment by shcaba** [comment]
Thank you Ali. Lots of great material here.
I think I still struggle with the 1963 onward 3A black rockfish reconstruction by Douglas 1998 being so different from the 2015 trawl catch history. We should revisit these differences and see why Douglas is not a good source for 3A black rockfish landings.

**Comment by aliwhitman** [comment]
Okay, so putting this on github.  I have a few thoughts from some out-loud brainstorming with Katie, our commercial GMT rep.  

First, I would love to understand more about the impact on the model and results using the Karnowski reconstruction as opposed to the Mirick reconstruction (the 2015 series). It would provide background and confirm that this is the big deal that we think it is.  I would like to do this with the new bridge model, but I'm a little unsure how to grab that from github, so if Jason could help me with that, I can run those. 

Second, I don't think anyone is going for the Karnowski reconstruction, but leaning toward the Mirick reconstruction or some modification of that reconstruction.  Along those lines, and acknowledging our time constraints, I propose a few lines of investigation.  

1. If we have concerns regarding the magnitude of the total rockfish catch in 3A, I can compare and then potentially average or select a single source among our three sources of data for this (PFMC reports, Douglas comps, and FSUS). They have varying degrees of overlap and length of individual time series.  These could be substituted into the Mirick reconstruction.
 
2. Mirick used the Douglas comps to estimate the % black back in time. However, we also have data on the sampling rate for each individual species comp (lbs species comp subsample/lbs total rockfish), so I could investigate filtering this for a (somewhat arbitrary) cutoff for sampling rate and only use those comps to determine a %black to apply to 3A total rockfish. 

3. Moving fish to WA had the largest effect on the differences between Karnowski and Mirick. Instead of using the Douglas comps to estimate the %WA black historically, we could investigate using trawl logbook data (in 3A only, available from 1993 - 2022ish) to calculate how many fish to move north. Mirick only used these data during that time period they were available and used the Douglas comps prior to that. 

What are folks' thoughts on these?  Collectively, these alternatives might provide alternative time series which would provide a range of removals to test among (though ultimately we would need to select one!).

**Comment by shcaba** [comment]
Ali-- If you send me the Karnowski time series, I can run the model with it.
I am thinking through your other items.

**Comment by shcaba** [comment]
![BLK_OR_comp_no_uncertainty](https://user-images.githubusercontent.com/8162478/217121335-31e6dfb1-d5a7-4b22-aa83-31db7003320c.png)

**Comment by shcaba** [comment]
Report from talking with WA:
The big issue is the species comps used to break out the unknown rockfish.
Currently what is being done is taking that unknown rockfish category, then breaking it out to black rockfish, then allocating those black rockfish to OR and WA.

What is preferred is if we can get the total unknown rockfish in 3A, assign those to OR and WA, then us a different species comp in WA than in OR. 
This allows the OR assessment to use the Mirick reconstruction in Oregon, but does not constrain WA to using his species comps when breaking out the unknown rockfish in Washington.

**Comment by aliwhitman** [comment]
Proposal for today (abbreviated because my computer restarted in the middle of writing something longer!): 

1892 - 1939 - 2015 values for trawl and non-trawl fleets 
1940 - 1986 - Total rockfish with Mirick comps (14.1% for 1940 - 1974, 6.8% for 1975 - 1986) for trawl, 2015 values for non-trawl 
1987 - 2000 - 2015 values with the addition of URCK/POP reconstruction for trawl and non-trawl 
2001 - 2022 - PacFIN values for trawl/non-trawl   

Options I explored last week: 
- there's no relationship between sampling rate and %black in the Douglas comps; if you filter (arbitrarily) for certain sampling rates, you lose sample sizes quickly; didn't seem a viable approach at this time 
- I thought about using a simplified approach for comps and using a grand mean %black from the Douglas comps (which would be 9.8%) to apply to all years, but essentially, figured out that Mirick used raw comps when they became available in 1975 to develop an average %black and that seemed to be better utilizing the data available than a grand mean 
- also tried to resolve/track down the discrepancies - may want to substitute the 3A plus 2's values for the 2015 assessment values during 1987 - 2000 time period

**Comment by aaronmberger-nwfsc** [comment]
Hey,Sorry guys for missing today. I had to change my flight schedule to earlier in the day (this time) to get to the Hake management meeting this week in Vancouver a bit earlier than initially planned (US delegation meeting popped on the schedule all of a sudden on Monday).AaronOn Feb 27, 2023, at 9:01 AM, Ali Whitman ***@***.***> wrote:﻿
Proposal for today (abbreviated because my computer restarted in the middle of writing something longer!):
1892 - 1939 - 2015 values for trawl and non-trawl fleets
1940 - 1986 - Total rockfish with Mirick comps (14.1% for 1940 - 1974, 6.8% for 1975 - 1986) for trawl, 2015 values for non-trawl
1987 - 2000 - 2015 values with the addition of URCK/POP reconstruction for trawl and non-trawl
2001 - 2022 - PacFIN values for trawl/non-trawl
Options I explored last week:

there's no relationship between sampling rate and %black in the Douglas comps; if you filter (arbitrarily) for certain sampling rates, you lose sample sizes quickly; didn't seem a viable approach at this time
I thought about using a simplified approach for comps and using a grand mean %black from the Douglas comps (which would be 9.8%) to apply to all years, but essentially, figured out that Mirick used raw comps when they became available in 1975 to develop an average %black and that seemed to be better utilizing the data available than a grand mean
also tried to resolve/track down the discrepancies - may want to substitute the 3A plus 2's values for the 2015 assessment values during 1987 - 2000 time period

**Comment by aliwhitman** [comment]
![image](https://user-images.githubusercontent.com/80843508/224168541-177a0764-913c-4c86-b995-b8ab05e62ca6.png)

Comparison of the above methodology (2023 for trawl and non-trawl) and what was used in the 2015 assessment. I think we're looking good!  Minor differences overall, only see the addition of the URCK/POP reconstruction in the late 1980s and 1990s for non-trawl.
